import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [userInput, setUserInput] = useState('')
  const [todoItems, setTodoItems] = useState([]) 

  const handleSubmit  = (e) => {
    e.preventDefault()
    setTodoItems([
      userInput,
      ...todoItems,
    ])
    setUserInput('')
  }

  const handleDelete = (item) => {
    const updatedArr = todoItems.filter(newitem => todoItems.indexOf(newitem) != todoItems.indexOf(item))
    setTodoItems(updatedArr)
  }

  const handleEdit = (item) => {
    const updatedArr = todoItems.filter(newitem => todoItems.indexOf(newitem) === todoItems.indexOf(item))
    setUserInput(updatedArr)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Next Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form >
        <input placeholder='Add Todo Item' type='text' value={userInput} onChange={e => setUserInput(e.target.value)} />
        <button type='submit' onClick={e => handleSubmit(e)}> Submit</button>
      </form>
      <ul>
        {todoItems.length >= 1 ? todoItems.map((item, index) => (
          <li key={index}>{item}
          <button type='button' onClick={() => handleEdit(item)} >edit</button>
          <button onClick={() => handleDelete(item)}>Delete</button></li>
        )): (<p>Add Todo</p>)}
      </ul>


    </div>
  )
}
